name: flutter_music_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Совместимые версии для iOS:
  shared_preferences: ^2.2.2
  localstorage: ^4.0.0+1
  provider: ^6.1.1
  oktoast: ^3.4.0
  pull_to_refresh: ^2.0.0
  dio: ^4.0.0
  device_info_plus: ^4.0.0
  package_info_plus: ^2.3.0
  shimmer: ^2.0.0
  bubble_bottom_bar: ^2.0.0
  audioplayers: ^5.2.1  # Правильная версия
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  http: ^1.1.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
