name: flutter_music_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Обновленные зависимости с поддержкой null safety:
  shared_preferences: ^2.2.2
  localstorage: ^4.0.0+1
  provider: ^6.1.1
  oktoast: ^3.0.1
  pull_to_refresh: ^2.0.0
  dio: ^5.3.3
  device_info: ^2.0.3
  package_info: ^2.0.2
  shimmer: ^2.0.0
  bubble_bottom_bar: ^2.0.0
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  http: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
